### ISSUE TITLE
NoMethodError: undefined method `count' for nil:NilClass when using fields_for_collection

### ISSUE THREAD

**Issue by malin-as** [hanami/helpers#112]
Hi,

I'm trying to use `fields_for_collection` but I get a strange error. I can recreate the error in a newly generated project when using the example from http://hanamirb.org/guides/1.0/helpers/forms/ (I just removed the non-existing route):

```erb
<%=
  form_for :delivery, '#' do
    text_field :customer_name

    fields_for_collection :addresses do
      text_field :street
    end

  submit 'Create'
end
%>
```

This is what I get on my browser:
```
Boot Error

Something went wrong while loading /home/malinas/hanami_error_form/config.ru
NoMethodError: undefined method `count' for nil:NilClass

/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/form_helper/form_builder.rb:246:in `fields_for_collection'
/home/malinas/hanami_error_form/apps/web/templates/home/index.html.erb:7:in `block (2 levels) in singleton class'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_builder.rb:364:in `instance_exec'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_builder.rb:364:in `resolve'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_node.rb:58:in `content'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/form_helper/html_node.rb:49:in `content'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_node.rb:44:in `to_s'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_builder.rb:332:in `map'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_builder.rb:332:in `to_s'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-helpers-1.0.0/lib/hanami/helpers/form_helper/form_builder.rb:140:in `to_s'
/home/malinas//hanami_error_form/apps/web/templates/home/index.html.erb:13:in `block in singleton class'
/home/malinas//hanami_error_form/apps/web/templates/home/index.html.erb:-6:in `instance_eval'
/home/malinas//hanami_error_form/apps/web/templates/home/index.html.erb:-6:in `singleton class'
/home/malinas//hanami_error_form/apps/web/templates/home/index.html.erb:-9:in `__tilt_37890300'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-view-1.0.1/lib/hanami/view/template.rb:41:in `render'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:139:in `rendered'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:153:in `layout'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:107:in `render'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-view-1.0.1/lib/hanami/view/rendering.rb:258:in `render'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:56:in `_render_action'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:48:in `_render'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:38:in `render'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/application.rb:169:in `call'
/home/malinas/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):15:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-router-1.0.1/lib/hanami/routing/http_router.rb:156:in `raw_call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-router-1.0.1/lib/hanami/router.rb:1019:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/assets/static.rb:49:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/app.rb:42:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/hanami-1.0.0/lib/hanami/assets/static.rb:49:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
/home/malinas/.rvm/gems/ruby-2.4.2@temp/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
/home/malinas/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/home/malinas/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/home/malinas/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

Beyond that error, I'm puzzled by how to use it, because I don't see any hint of an iterator or of a loop in that example. It would really be helpful to have an example that produces an array with two items (unless I misunderstood what this helper was for).

**Comment by TiteiKo** [comment]
Hi @malin-as ,

Basically, it will loop on the array, so make sure `delivery.adresses` is an array and not nil and it should solve the error.

Simplified example from my real-life project:

```ruby
# frozen_string_literal: true

module Admin::Controllers::Products
  class New
    include Admin::Action
    expose :product

    def call(*)
      @product = Product.new(locales: available_locales.map { |locale| ProductTranslation.new(locale: locale) }
    end
  end
end
```

```slim
= form_for creation_form, class: '' do
  - fields_for_collection :translations do |i|
    - hidden_field :locale
    - text_field :name, required: true
    - hidden_field :content
    - div class: 'wysiwyg', 'data-target': "#product-translations-#{i}-content"
```

I currently have 2 locales (fr & en) in the `available_locales` array. 

The generated html looks like this:

```html
<form action="/admin/products" method="POST" accept-charset="utf-8" id="product-form" class="">
  <input name="product[translations][][locale]" id="product-translations-0-locale" value="fr" type="hidden">
  <input name="product[translations][][name]" id="product-translations-0-name" value="" required="required" type="text">
  <input name="product[translations][][content]" id="product-translations-0-content" value="" type="hidden">
  <div class="wysiwyg" data-target="#product-translations-0-content"></div>
  <input name="product[translations][][locale]" id="product-translations-1-locale" value="en" type="hidden">
  <input name="product[translations][][name]" id="product-translations-1-name" value="" required="required" type="text">
  <input name="product[translations][][content]" id="product-translations-1-content" value="" type="hidden">
  <div class="wysiwyg" data-target="#product-translations-1-content"></div>
</form>
```

The form submission then arrives here:

```ruby
# frozen_string_literal: true

module Admin::Controllers::Products
  class Create
    include Admin::Action

    def call(params)
      if params.valid?
        # create product and redirect
      else
        # reinitialize the empty product
      end
    end

    params do
      required(:product).schema do
        required(:translations).each do
          schema do
            required(:locale)  { filled? & str? }
            required(:name)    { filled? & str? }
            optional(:content) { str? }
          end
        end
      end
    end
  end
end
```

With the following parameters:

```ruby
Hash[
  product: Hash[
    translations: [
      Hash[locale: 'fr', name: 'foo', content: 'foo bar'],
      Hash[locale: 'en', name: 'bar', content: 'bar foo']
    ]
  ]
]
```

Is it more clear?

**Comment by malin-as** [comment]
I understand most of your example, thanks for that (especially for connecting the dots between the names in the form and the validations), but I'm stuck at the first line. You say that `delivery.addresses` should be an array, but how do the helpers even know how to find that object? Am I supposed to create that object? And is there some automagical translation of `:delivery` and `:addresses` (when passed to `form_for` and `fields_for_collection` into method calls?

If I look at your example, you have a `Product` object exposed by the controller with the `product` name which does never appear in your form generation code.

**Comment by AlfonsoUceda** [comment]
Hi @malin-as can you provide us what you have in your view class? Thanks!

**Comment by malin-as** [comment]
Hi @AlfonsoUceda, there's nothing in my view class, it's just the one automatically generated:

```ruby
module Web::Views::Home
  class Index
    include Web::View
  end
end
```

Does it mean that in order to use `fields_for_collection` I need to put some information in my view class?

**Comment by AlfonsoUceda** [comment]
@malin-as if you comment `fields_for_collection` block, works? where are you exposing `:delivery`?

**Comment by malin-as** [comment]
@AlfonsoUceda yes, after commenting the `fields_for_collection` block, it works. So far I'm not exposing any `delivery`. Should I have a `Delivery` object in my model for this to work?

**Comment by AlfonsoUceda** [comment]
`fields_for_collection` expects a collection, if you don't provide a `delivery` object with `addressed` collection, it won't work.

Checking your code it seems that form is when you want create a new delivery, so you need to provide an empty deliver object, try that please.

**Comment by malin-as** [comment]
I think it's finally taking shap, I got this in my controller now:

```ruby
module Web::Controllers::Home
  class Index
    include Web::Action

    expose :delivery

    def call(params)
      @delivery = { addresses: Array.new(5) }
    end
  end
end
```

And my template now is:
```ruby
<%=
  form_for :delivery, '#', values: { delivery: delivery } do
    text_field :customer_name

    fields_for_collection :addresses do
      text_field :street
    end

    submit 'Create'
  end
%>
```

The form contains 5 street fields since the `addresses` array is of size 5. But I have to explicitly set `values` in my call to `form_for`, is that the correct way of using it? In @TiteiKo's example, `product` seems to be automatically used by `form_for`.

**Comment by AlfonsoUceda** [comment]
In @TiteiKo's example use `Product` I think that is an entity so other fields will be readed from that entity. IMO you should use a `Delivery` entity to use in that form_for instead a plain hash.

**Comment by AlfonsoUceda** [comment]
I'm going to close this issue but of course you can follow asking, if you have more questions you can use [gitter chat](http://chat.hanamirb.org/)
