### ISSUE TITLE
JRuby ConcurrencyError with tag block form

### ISSUE THREAD

**Issue by nerdinand** [hanami/helpers#114]
In my code I'm trying to use the block form of `tag`, something like this:
```ruby
  form_for :thing, '/', method: :post do
    tag :label do
      check_box :attribute, value: 'foo'
      text 'bar'
    end
  end
```

When I try to render this with JRuby, I get a ConcurrencyError:

```
ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users
	org/jruby/RubyArray.java:2486:in `map'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_builder.rb:332:in `to_s'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/form_helper/form_builder.rb:140:in `to_s'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_node.rb:61:in `content'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/form_helper/html_node.rb:49:in `content'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_node.rb:44:in `to_s'
	org/jruby/RubyArray.java:2486:in `map'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/html_helper/html_builder.rb:332:in `to_s'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-helpers-1.0.0/lib/hanami/helpers/form_helper/form_builder.rb:140:in `to_s'
	/Users/ferdi/projects/bookshelf/apps/web/templates/books/edit.html.erb:1:in `block in singleton class'
	org/jruby/RubyBasicObject.java:1691:in `instance_eval'
	/Users/ferdi/projects/bookshelf/apps/web/templates/books/edit.html.erb:1:in `singleton class'
	/Users/ferdi/projects/bookshelf/apps/web/templates/books/edit.html.erb:1:in `__tilt_2048'
	org/jruby/RubyMethod.java:115:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-view-1.0.0/lib/hanami/view/template.rb:41:in `render'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-view-1.0.0/lib/hanami/view/rendering.rb:139:in `rendered'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-view-1.0.0/lib/hanami/view/rendering.rb:153:in `layout'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-view-1.0.0/lib/hanami/view/rendering.rb:107:in `render'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-view-1.0.0/lib/hanami/view/rendering.rb:258:in `render'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:56:in `_render_action'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:48:in `_render'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/rendering_policy.rb:38:in `render'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/application.rb:169:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/stdlib/delegate.rb:83:in `method_missing'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
	(eval):15:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-router-1.0.1/lib/hanami/routing/http_router.rb:156:in `raw_call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-router-1.0.1/lib/hanami/router.rb:1019:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/assets/static.rb:49:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/app.rb:42:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/hanami-1.0.0/lib/hanami/assets/static.rb:49:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/stdlib/webrick/httpserver.rb:140:in `service'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/stdlib/webrick/httpserver.rb:96:in `run'
	/Users/ferdi/.rbenv/versions/jruby-9.1.13.0/lib/ruby/stdlib/webrick/server.rb:296:in `block in start_thread'
```

The same code does not lead to an exception when using MRI.

It really seems to have to do with the block form of the `tag` method. The following code works fine:

```ruby
  form_for :thing, '/', method: :post do
    tag :label
    check_box :attribute, value: 'foo'
    text 'bar'
  end
```

**Comment by AlfonsoUceda** [comment]
Thanks @nerdinand checked, marking as bug

**Comment by nerdinand** [comment]
I wrote a failing spec to reproduce this problem. While doing this, I noticed that there seems to be another bug (the spec fails in both MRI and JRuby):

In my opinion, this code:

```ruby
form_for(:foo, '/') do
  tag 'label' do
    radio_button 'radio_button', 'high'
    text 'bar'
  end
end
```

Should result in:
```html
<form action="/" method="POST" accept-charset="utf-8" id="foo-form">
<label>
<input type="radio" name="foo[radio_button]" value="high">
bar
</label>
</form>
```

But the actual outcome in the test (with MRI) is:
```html
<form action="/" method="POST" accept-charset="utf-8" id="foo-form">
<label>
bar
</label>
<input type="radio" name="foo[radio_button]" value="high">
</form>
```

Additionally, when run with JRuby, this test results in the `ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users`.

**Comment by AlfonsoUceda** [comment]
@nerdinand thanks for the comment, I agree with you, I think if you use `tag` to envelop something that should be the behaviour

**Comment by AlfonsoUceda** [comment]
have you tried this with the last version of jRuby?

**Comment by jodosha** [comment]
Closed as stale conversation.
