### ISSUE TITLE
implementation of datalist helper

### ISSUE THREAD

**Issue by sebastjan-hribar** [hanami/helpers#57]
Hi,

I'd like to open this ticket to ask for implementation of the datalist helper: https://github.com/hanami/helpers/blob/23a7df457513ad79bd1d3da5a4c8f1cea5776923/lib/hanami/helpers/html_helper/html_builder.rb#L42 .

Thank you.
Kind regards,
Sebastjan

**Comment by joneslee85** [comment]
@sebastjan-hribar isn't that this helper there already? Can you try `html.datalist`?

**Comment by sebastjan-hribar** [comment]
Hi,
I've tried the code below, where parents are exposed in the action:
```
td do
          html.input(list: "parents", name: "ParentID") do
            html.datalist(id: "parents") do
              parents.each do |parent|
                option do
                  parent.surname
                end
              end
            end
          end
        end
```

I get this error:

```
Boot Error

Something went wrong while loading /home/sebastjan/Dokumenti/projekti/hanami/ptconference/config.ru

NoMethodError: undefined method `html' for #<Hanami::View::Rendering::Scope:0x00000003ff2f28>

/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/rendering/layout_scope.rb:211:in `method_missing'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/rendering/scope.rb:69:in `method_missing'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:371:in `method_missing'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:371:in `method_missing'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:371:in `method_missing'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:371:in `method_missing'
/home/sebastjan/Dokumenti/projekti/hanami/ptconference/apps/web/templates/students/new.html.erb:45:in `block (5 levels) in singleton class'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:356:in `instance_exec'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:356:in `resolve'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:56:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/html_node.rb:48:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/form_builder.rb:143:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/html_node.rb:48:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/form_builder.rb:143:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/html_node.rb:48:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/form_builder.rb:143:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/html_node.rb:48:in `content'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-helpers-0.3.0/lib/hanami/helpers/form_helper/form_builder.rb:143:in `to_s'
/home/sebastjan/Dokumenti/projekti/hanami/ptconference/apps/web/templates/students/new.html.erb:64:in `block in singleton class'
/home/sebastjan/Dokumenti/projekti/hanami/ptconference/apps/web/templates/students/new.html.erb:-6:in `instance_eval'
/home/sebastjan/Dokumenti/projekti/hanami/ptconference/apps/web/templates/students/new.html.erb:-6:in `singleton class'
/home/sebastjan/Dokumenti/projekti/hanami/ptconference/apps/web/templates/students/new.html.erb:-8:in `__tilt_11000200'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `evaluate'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/template.rb:41:in `render'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:117:in `rendered'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:131:in `layout'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:104:in `render'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:236:in `render'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/rendering_policy.rb:44:in `_render_action'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/rendering_policy.rb:37:in `_render'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/rendering_policy.rb:28:in `render'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/application.rb:217:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):15:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-router-0.6.2/lib/hanami/routing/http_router.rb:135:in `raw_call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-router-0.6.2/lib/hanami/router.rb:931:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/static.rb:27:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/container.rb:37:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/commands/server.rb:56:in `start'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/lib/hanami/cli.rb:43:in `server'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/hanami-0.7.0/bin/hanami:5:in `<top (required)>'
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/hanami:23:in `load'
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/hanami:23:in `<main>'
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jodosha** [comment]
@sebastjan-hribar Nested `html` calls won't work. You should omit the inner one:

```ruby
html.ul do
  li 'English' # NO html INVOCATION HERE
end
```

---

Now, [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) is similar to [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select). For the latter we offer [a specific support in `FormBuilder`](https://github.com/hanami/helpers/blob/master/lib/hanami/helpers/form_helper/form_builder.rb#L754), we should do the same for `datalist`.

/cc @joneslee85

**Comment by sebastjan-hribar** [comment]
By omitting the inner html call (the one for datalist), I get the same error. I also tried adding the value block inside the option:

```
option do
  value do
    parent.surname
  end
end
```

and the error persists.

If I only put the html call to datalist tag (with or w/o the value block), the form is rendered, but the parent field is just an input field.

**Comment by joneslee85** [comment]
@sebastjan-hribar would you be able to submit a PR?

**Comment by sebastjan-hribar** [comment]
I'll keep trying to get this right, but I can't guarantee a PR, because I'm afraid it extends beyond my current abilities and knowledge.

**Comment by sebastjan-hribar** [comment]
Update on the current `datalist tag` implementation:

The code below works in a sense that produces the list of all parents and performs the `datalist` functionalities. Errors in my code above were two: `html` calls and nesting the `datalist` under `input`.
``` 
input(list: "parents", name: :ParentID)
  datalist(id: "parents") do
    parents.each do |parent|
      option do
        parent.surname
      end
    end
  end
``` 

However, the student is created, but the `ParentID` is not added as the FK to the students table. I've also tried with `parent.id` but it still doesn't get saved as the FK. I've described the same issue in this gist:
https://gist.github.com/sebastjan-hribar/9a8480eb9718e9db21e2

I've suspected something wrong with the manual markup, but now it seems it's the `datalist` issue. The `select tag` on the other hand works fine and adds the `ParentID` as the FK to the students table.

What do you think?
kind regards,
Sebastjan

**Comment by jodosha** [comment]
@sebastjan-hribar Hey, thanks for the extended explanation. Would you be so nice to add the HTML output of both the forms? That is helpful to understand where is the problem.

**Comment by jodosha** [comment]
I'm still thinking that we need a `datalist` method in `FormBuilder`. One similar to `select`.

**Comment by sebastjan-hribar** [comment]
Hi,

I kept at it and I'finally solved it. I tried to mimic the select behavior and this code does something similar:

```
values = Hash.new
          parents.each {|parent|
            values[parent.id] = parent.surname
            }

input(list: "parents", type: "text", name: "student[ParentID]")
          datalist(id: "parents") do
            values.each do |key, parent|
              option(parent, {value: key})
            end
          end
```

This creates a `datalist` with a value of `key`, which is used as a FK. And it displays all `parents` and it enables auto complete. I will have to deal with the possibility of users entering something else that the options given.

For the `value` not being saved, the error was in the `name` attribute for the `input tag`.

Unfortunately I haven't foreseen this. By examining the source code I noticed:

whereas

`text_field    :sclass` converts to `name="student[sclass]"`

the `name: :ParentID` or `name: "ParentID"` convertes to `name="ParentID"` and NOT to `name="student[ParentID]"`.

So when using `datalist` tag, one has to specify the entity in the `name` attribute of the `input` tag:

```
input(list: "parents", type: "text", name: "student[ParentID]").
```

------------------------------------------------------------------------------------------------------------
**I'm still left with this design problem:**

The code above makes this list:
```
<input list="parents" type="text" name="student[ParentID]">
<datalist id="parents">
<option value="1">Berik</option>
<option value="2">Brnol</option>
<option value="3">Dolinar</option>
<option value="4">Doms</option>
<option value="5">Jerim</option>
<option value="6">Lipar</option>
<option value="7">Rekar</option>
<option value="8">Timp</option>
<option value="9">Topol</option>
<option value="10">Upal</option>
</datalist>
```
This works only if I select an option from the list (no better than `select` tag). The auto complete works for values (numbers) which is of no help. I need it to be applied for surnames.

So by selecting an option or typing in a number as the parent id, the student is created. By typing, for example "Topol" there is no auto complete and the value taken is "Topol" which causes an error when saving.

In principle the `datalist` works I just have to rethink whether to use it. End users will work with a few rather big lists though.

regards,
seba

**Comment by jodosha** [comment]
@sebastjan-hribar

> `text_field :sclass` converts to `name="student[sclass]"`
> the `name: :ParentID` or `name: "ParentID"` convertes to `name="ParentID"` and NOT to `name="student[ParentID]"`.

That is because `text_field` is designed to work with specific HTML forms knowledge. It's part of `FormBuilder`. If you use generic HTML builders (eg `html.datalist`), they don't know nothing about forms, just about HTML.

What means "form knowledge" BTW? That means a helper knows the form is belonging to (eg `form_for :student`) and properly prefixes the `name` attributes or fill the `value` ones.

**This is the reason why I said we need a `datalist` from helper**.

**Comment by sebastjan-hribar** [comment]
@jodosha 
I just wanted to state that it was an overlook on my behalf, regarding the name attribute, and of course, I agree with the `datalist` form helper. Thank you also for the "form knowledge" explanation.
Kind regards,
Sebastjan
