### ISSUE TITLE
rake test: undefined method `param' for DeliveryParams:Class (NoMethodError)

### ISSUE THREAD

**Issue by sebastjan-hribar** [hanami/helpers#67]
After forking and w/o any changes yet rake test for helpers gives the following error:

```
(eval):2: warning: method redefined; discarding old link
(eval):2: warning: previous definition of link was here
/home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/presenter.rb:1: warning: loading in progress, circular require considered harmful - /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/view/escape.rb
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in  `<main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in  `select'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in  `block in <main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in  `each'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in  `block (2 levels) in <main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in  `require'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/escape_helper_test.rb:1:in  `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/escape_helper_test.rb:1:in  `require'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/test_helper.rb:12:in  `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/test_helper.rb:12:in  `require_relative'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/fixtures.rb:1:in  `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/fixtures.rb:1:in  `require'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/view.rb:8:in  `<top (required)>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/view.rb:8:in  `require'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/view/escape.rb:2:in  `<top (required)>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/view/escape.rb:2:in  `require'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/presenter.rb:1:in  `<top (required)>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/bundler/gems/view-6a51e5cd3daf/lib/hanami/presenter.rb:1:in  `require'
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/dry-types-0.7.2/lib/dry/types/options.rb:18: warning: method redefined; discarding old meta
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/dry-types-0.7.2/lib/dry/types/struct.rb:62: warning: instance variable @schema not initialized
/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/dry-types-0.7.2/lib/dry/types/struct.rb:56: warning: instance variable @constructor_type not initialized
/home/sebastjan/Dokumenti/projekti/hanami/helpers/test/fixtures.rb:342:in `<class:DeliveryParams>': undefined method `param' for DeliveryParams:Class (NoMethodError)
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/fixtures.rb:341:in `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/test_helper.rb:12:in `require_relative'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/test_helper.rb:12:in `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/escape_helper_test.rb:1:in `require'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/escape_helper_test.rb:1:in `<top (required)>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in `require'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in `each'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib" "/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by sebastjan-hribar** [comment]
With filtered warnings it gives back:

```
/home/sebastjan/Dokumenti/projekti/hanami/helpers/test/fixtures.rb:342:in `<class:DeliveryParams>': undefined method `param' for DeliveryParams:Class (NoMethodError)
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/fixtures.rb:341:in `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/test_helper.rb:12:in `require_relative'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/test_helper.rb:12:in `<top (required)>'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/escape_helper_test.rb:1:in `require'
	from /home/sebastjan/Dokumenti/projekti/hanami/helpers/test/escape_helper_test.rb:1:in `<top (required)>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in `require'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in `each'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib" "/home/sebastjan/.rvm/gems/ruby-2.2.1/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/sebastjan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by vasspilka** [comment]
I can confirm this occurs cloning, installing bundle and trying to run specs.

Should be becouse of the change to `dry-v`

**Comment by vladimirich** [comment]
Got same behaviour too

**Comment by sebastjan-hribar** [comment]
Here's jodosha's advice from chat, but I haven't gotten around to it yet and probably won't have the time for another week.
---
you have to amend Gemfile with the latest dependencies: See hanami/validations Gemfile as an example.
Plus you need to amend the fixtures from hanami/helpers to make sure they work with the latest changes.
---

**Comment by jodosha** [comment]
I fixed this problem in master with https://github.com/hanami/helpers/commit/b534567a259d60edd648c992ba70044875e6a4fc

Thank you all! 💖
