### ISSUE TITLE
form_for helper giving an undefined method 'params' in tests

### ISSUE THREAD

**Issue by TiteiKo** [hanami/helpers#71]
Hi,

So.. I'm trying to make a really simple form:

```ruby
# in the view
def creation_form
  Form.new(:thing, '#', thing: thing) # thing being exposed by the action
end

def creation_form_submit_text
  'Create'
end
```

```haml
-# and the template (in haml)
= form_for creation_form, class: '' do
  - text_field :title
  - submit creation_form_submit_text
```

With a really small test on the view/template:

```ruby
require 'spec_helper'
require_relative '../../../../apps/web/views/things/new'

describe Web::Views::Things::New do
  let(:exposures) { Hash[thing: Thing.new] }
  let(:template)  { Hanami::View::Template.new('apps/web/templates/things/new.html.haml') }
  let(:view)      { Web::Views::Things::New.new(template, exposures) }
  let(:rendered)  { view.render }

  it('renders') { rendered }
end
```

And everything should be shining in glory to the Thing! And it is! At least in my browser, yay!

But it's not in my test...

```
NoMethodError: undefined method `params' for #<Hanami::View::Rendering::Scope:0x007ff49c85a9b0>
```

Full error stack: http://0bin.net/paste/qIW55zzj6-TmTtCR#gm-ZUExIHvX8PhTJi0bZMPTHPUI0qN3hu/KMLSsyjv/
Full Gemfile.lock: http://0bin.net/paste/2RiASve4iefyZ+Co#UrbYcXYSbimlQwyRqba1vviD93uD+ql7KWx30cJ6mrE

**Comment by bruz** [comment]
I ran into this too at one point. Adding `params` to the exposures seems to fix it, so you could try:

```ruby
require 'spec_helper'
require_relative '../../../../apps/web/views/things/new'

class NewThingsParams < Hanami::Action::Params
  params do
  end
end

describe Web::Views::Things::New do
  let(:params)    { NewThingsParams.new({}) }
  let(:exposures) { Hash[thing: Thing.new, params: params] }
  let(:template)  { Hanami::View::Template.new('apps/web/templates/things/new.html.haml') }
  let(:view)      { Web::Views::Things::New.new(template, exposures) }
  let(:rendered)  { view.render }

  it('renders') { rendered }
end
```

I noticed that as of Hanami 0.8.0 I had to add the `params` block in `NewThingsParams` to get it to work.

If someone knows a less verbose way of doing setup for view tests, I would love having a better way of doing this.

**Comment by jodosha** [comment]
@TiteiKo Hi and sorry for this lack of clarity - @bruz is right: you should pass it as an exposure. There is no need to create a concrete class (eg. `NewThingsParams`), but you can instantiate a Hash directly:

```ruby
let(:params) { Hash[] }
```

---

This testing design is verbose, but ensures to test the view in isolation.

**Comment by TiteiKo** [comment]
@jodosha When using ```Hash[]```, we get the following error:

```
NoMethodError: undefined method `get' for {}:Hash
Did you mean?  gets
               gem
    /Users/marion/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-helpers-0.4.0/lib/hanami/helpers/form_helper/values.rb:30:in `get'
    /Users/marion/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-helpers-0.4.0/lib/hanami/helpers/form_helper/form_builder.rb:981:in `_value'
    /Users/marion/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-helpers-0.4.0/lib/hanami/helpers/form_helper/form_builder.rb:955:in `_attributes'
    /Users/marion/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-helpers-0.4.0/lib/hanami/helpers/form_helper/form_builder.rb:644:in `text_field'
```

**Comment by jodosha** [comment]
@TiteiKo Sorry for this misleading suggestion. Here's a solution for it 😄 https://github.com/hanami/helpers/pull/72

**Comment by TiteiKo** [comment]
@jodosha Yay! Thanks 👍
